services:
  frontend:
    build:
      context: .
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:80"
  
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.security.transport.ssl.enabled=false
    - http.cors.enabled=yes
    - http.cors.allow-origin="*"
    - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
    - http.cors.allow-headers=Access-Control-Allow-Origin,x-csrf-token,authorization,content-type,accept,origin,x-requested-wit
    ports:
      - "9200:9200"